/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 models/6472d00a004f1ebc6498cac0.glb 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Avatar(props) {

  const { animation } = props

  const group = useRef()
  const { nodes, materials } = useGLTF('models/6472d00a004f1ebc6498cac0.glb')

  // animations
  const { animations: standingAnimation } = useFBX('animations/Neutral_Idle.fbx')
  standingAnimation[0].name = "Standing"

  // actions
  const { actions } = useAnimations([standingAnimation[0]], group)
  const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);

  useFrame((state) => {
    if ((state.mouse.x != 0 && state.mouse.y != 0) && !isMobile) {
      let y = (state.mouse.y < 0) ? 0 : state.mouse.y
      group.current.getObjectByName("Spine2").lookAt(state.mouse.x, y, 1)
      group.current.getObjectByName("Hips").lookAt(state.mouse.x / 10, y / 10, 1)
    }
  })

  useEffect(() => {
    actions[animation].reset().play()
    return () => {
      actions[animation].reset().fadeOut(0.5)
    }
  }, [animation])

  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh name="Wolf3D_Avatar" geometry={nodes.Wolf3D_Avatar.geometry} material={materials.Wolf3D_Avatar} skeleton={nodes.Wolf3D_Avatar.skeleton} morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('models/6472d00a004f1ebc6498cac0.glb')

